"""initial schema

Revision ID: 55f4a8b31da7
Revises: 
Create Date: 2026-05-20 18:58:21.738432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '55f4a8b31da7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funds',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('native_currency', sa.String(), nullable=False),
    sa.Column('benchmark', sa.String(), nullable=False),
    sa.Column('benchmark_label', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('invitations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'SALES', 'MANAGER', name='role'), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('market_data_points',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rusfar', sa.Float(), nullable=True),
    sa.Column('rgbitr', sa.Float(), nullable=True),
    sa.Column('mcftr', sa.Float(), nullable=True),
    sa.Column('cbonds_zo_rub', sa.Float(), nullable=True),
    sa.Column('cbonds_zo_usd', sa.Float(), nullable=True),
    sa.Column('rucnytr_rub', sa.Float(), nullable=True),
    sa.Column('rucnytr_cny', sa.Float(), nullable=True),
    sa.Column('gldrub', sa.Float(), nullable=True),
    sa.Column('usdrub', sa.Float(), nullable=True),
    sa.Column('cnyrub', sa.Float(), nullable=True),
    sa.Column('cpi_rub', sa.Float(), nullable=True),
    sa.Column('cpi_usd', sa.Float(), nullable=True),
    sa.Column('cpi_cny', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('users',
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ANALYST', 'SALES', 'MANAGER', name='role'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('hashed_password', sa.String(length=1024), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('allocation_models',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('notes', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fund_quotes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fund_key', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('price_rub', sa.Float(), nullable=False),
    sa.Column('price_native', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fund_key'], ['funds.key'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_key', 'date')
    )
    op.create_table('proposals',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('client_id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('comment', sa.String(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('amount_currency', sa.String(), nullable=False),
    sa.Column('base_currency', sa.String(), nullable=False),
    sa.Column('risk_profile', sa.String(), nullable=False),
    sa.Column('currency_strategy', sa.String(), nullable=False),
    sa.Column('fund_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('index_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('proposal_date', sa.Date(), nullable=False),
    sa.Column('sent_to_client', sa.Boolean(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('proposals')
    op.drop_table('fund_quotes')
    op.drop_table('clients')
    op.drop_table('audit_events')
    op.drop_table('allocation_models')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('market_data_points')
    op.drop_table('invitations')
    op.drop_table('funds')
    # ### end Alembic commands ###
